### ISSUE TITLE
Nuget version

### ISSUE THREAD

**Issue by TimGeyssens** [erikjanwestendorp/Our.Umbraco.Domains#1]
Simple but useful package! Just wondering if a nuget version is in the works?

**Comment by erikjanwestendorp** [comment]
Hi @TimGeyssens There are certainly plans to make a nuget package (when there is some time ;-)).

**Comment by TimGeyssens** [comment]
Awesome!

**Comment by erikjanwestendorp** [comment]
@TimGeyssens A nuget package is available now: 
https://www.nuget.org/packages/Our.Umbraco.Domains/

**Comment by TimGeyssens** [comment]
Ow yeah! Will defo be using it! Thanks
