### ISSUE TITLE
Is the node name clickable? 

### ISSUE THREAD

**Issue by TimGeyssens** [erikjanwestendorp/Our.Umbraco.Domains#2]
Would be ace if you could click on the node name and that goes to the actuall node... since in some cases a node name isn't enough the identify the site...

**Comment by erikjanwestendorp** [comment]
Hi @TimGeyssens thanks for reporting! It is already possible to click on a node name, see image below. Apparently it's not clear enough so I have to make this more visually clear.
 
![chrome-capture](https://user-images.githubusercontent.com/7831614/89784155-75c89880-db18-11ea-8281-5a2700d7c320.gif)

**Comment by TimGeyssens** [comment]
sweet!

**Comment by erikjanwestendorp** [comment]
@TimGeyssens Just updated the package to make it easier to see that the node is clickable. See the latest version on our. 
https://our.umbraco.com/FileDownload?id=20913 

https://github.com/erikjanwestendorp/Our.Umbraco.Domains/commit/9a04ff2f1c77ade2d5eae6fce2c75f6f0b292dc1
